baseURL = 'https://canxerian.com/'
languageCode = 'en-us'
title = 'Canxerian software dev blog'
theme = 'paper'

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  github = 'canxerian'                        # github.com/YOUR_GITHUB_ID
  linkedin = 'canxerian'                      # linkedin.com/in/YOUR_LINKEDIN_ID
#   twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
#   instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
#   mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
#   threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
#   rss = true                                # show rss icon

  # home page profile
  avatar = 'mgb.nguyen@gmail.com'                 # gravatar email or image url
  name = 'Mark Nguyen'
  bio = 'Software engineering advice'


  # misc
#   disableHLJS = true                        # disable highlight.js
#   disablePostNavigation = true              # disable post navigation
#   monoDarkIcon = true                       # show monochrome dark mode icon
#   gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
#   math = true                               # enable KaTeX math typesetting globally
#   localKatex = false                        # use local KaTeX js/css instead of CDN
#   graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
#   favicon = "favicon.ico"                   # customize the default favicon
#   appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
# [params.giscus]
#   repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
#   repoId = 'YOUR_GISCUS_REPO_ID'
#   category = 'YOUR__GISCUS_CATEGORY'
#   categoryId = 'YOUR_GISCUS_CATEGORY_ID'
#   mapping = 'pathname'
#   theme = 'light'
#   lang = 'zh-CN'
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true